apiVersion: v1
kind: Service
metadata:
  name: writing
  labels:
    app: writing
spec:
  selector:
    app: writing
  ports:
    - protocol: TCP
      port: 80         # 외부 접근 시 사용할 포트
      targetPort: 8080 # 내부 컨테이너 포트
  type: LoadBalancer
